openapi: 3.0.0
info:
  title: Application EMS Integration Data Removal SQS Message
  version: 1.2.1
  description: |-
    Application EMS Integration Data Removal API SQS Message Types for EROP

    Messages defined in this spec are produced by EROP and consumed by EMS.

    Any changes to this spec should be based on joint collaboration and agreement between EROP and EM.

    Whilst this is an openAPI spec, it does not imply being used to define REST APIs, nor is it intended to.

    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**

    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required
    elements.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/remove-application-request':
    post:
      tags:
        - SQS queues
      requestBody:
        $ref: '#/components/requestBodies/RemoveApplicationEmsIntegrationDataMessage'
      responses:
        '204':
          description: No Content

#
# --------------------------------------------------------------------------------
#
components:
  #
  # Schema and Enum Definitions
  # -
  schemas:
    RemoveApplicationEmsIntegrationDataMessage:
      title: RemoveApplicationEmsIntegrationDataMessage
      type: object
      description: |
        Message requesting removal of IED postal/proxy application integration data.
      x-api-owner: EMS
      x-api-consumer: EROP
      properties:
        applicationId:
          type: string
          description: the IER ID of the application integration data to be removed
          pattern: '^[a-fA-F\d]{24}$'
          example: 502cf250036469154b4f85fc
        source:
          type: string
          description: Enum indicating type of application integration data for which removal is requested
          enum:
            - POSTAL
            - PROXY
      required:
        - applicationId
        - source

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    RemoveApplicationEmsIntegrationDataMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RemoveApplicationEmsIntegrationDataMessage'