email:
  monitor-pending-downloads-content:
    subject: "[test] Postal and Proxy Pending Downloads Monitoring"
  pending-register-checks-content:
    subject: "[test] Register Check Monitoring"

dluhc:
  holding-pool-threshold-date: 2025-09-01T00:00:00Z