title: CreatePostalVoteApplicationMessage
x-api-owner: IER
x-api-consumer: EROP
type: object
properties:
  id:
    type: string
    pattern: '^[a-fA-F\d]{24}$'
    description: 'The unique IER identifier for this application. A 24 character hex string.'
  gssCode:
    $ref: ./Primatives/GssCode.yaml
  applicationReference:
    type: string
    description: 'The application reference as known by the citizen. Not guaranteed to be unique.'
  datetimeSubmitted:
    type: string
    format: date-time
  firstName:
    type: string
    maxLength: 255
  middleNames:
    type: string
    maxLength: 255
  surname:
    type: string
    maxLength: 255
  dateOfBirth:
    type: string
    format: date
  registeredWithUnknownDob:
    type: boolean
  unknownDobReason:
    type: string
  ageRange:
    $ref: ./AgeRange.yaml
  email:
    type: string
    format: email
    maxLength: 256
  phoneNumber:
    type: string
    maxLength: 50
  noContact:
    type: boolean
    default: false
  nino:
    type: string
    maxLength: 10
  cantSupplyNinoReason:
    type: string
  postalVoteType:
    type: string
    enum:
      - SpecificElectionOrReferendum
      - SpecificDatePeriod
      - ThreeYears
  address:
    $ref: ./Address.yaml
  ballotAddress:
    $ref: ./Address.yaml
  ballotOverseasPostalAddress:
    $ref: ./Address.yaml
  ballotPostalAddressReason:
    type: string
    maxLength: 500
  postalVoteFrom:
    type: string
    format: date
  postalVoteTo:
    type: string
    format: date
  signatureImage:
    type: string
    format: byte
  identityDocuments:
    type: array
    items:
      $ref: ./DocumentReference.yaml
  cantUploadDocuments:
    type: boolean
    default: false
  submittedInWelsh:
    type: boolean
    default: false
  applicantIpAddress:
    type: string
    maxLength: 45
    description: The IP address of the applicant when completing their application on the IER web application front end. An optional value that if provided may be either an IPv4 or IPv6 address.
  requestedApplicationCopyViaEmail:
    type: boolean
    default: false
required:
  - id
  - gssCode
  - applicationReference
  - datetimeSubmitted
  - firstName
  - surname
  - address
  - signatureImage
  - applicantIpAddress
  - requestedApplicationCopyViaEmail